    const chatbox = document.getElementById('chatbox');
    const input = document.getElementById('input');
    const send = document.getElementById('send');

    // 100+ predefined Q&A pairs (sample questions, you can expand them as needed)
    const knowledgeBase = [
  { q: "hello", a: "Hi there! How can I help you today?" },
  { q: "hi", a: "Hello! What can I do for you?" },
  { q: "how are you", a: "I'm a bot, but I'm doing great! Thanks for asking." },
  { q: "what is your name", a: "I'm your Custom Chatbot." },
  { q: "help", a: "Sure! Ask me anything or type your question." },
  { q: "what can you do", a: "I can chat with you and answer basic questions." },
  { q: "who made you", a: "I was created with love and code by a human developer." },
  { q: "bye", a: "Goodbye! Have a great day!" },
  { q: "thank you", a: "You're welcome! Happy to help." },
  { q: "thanks", a: "Anytime! Let me know if you have more questions." },
  { q: "what is html", a: "HTML stands for HyperText Markup Language, the standard markup language for creating web pages." },
  { q: "what is css", a: "CSS stands for Cascading Style Sheets, used for styling web pages." },
  { q: "what is javascript", a: "JavaScript is a programming language used to make web pages interactive." },
  { q: "what is vs code", a: "Visual Studio Code is a popular code editor developed by Microsoft." },
  { q: "who is elon musk", a: "Elon Musk is an entrepreneur known for Tesla, SpaceX, and more." },
  { q: "what is ai", a: "AI stands for Artificial Intelligence, machines designed to mimic human intelligence." },
  { q: "what is machine learning", a: "Machine Learning is a subset of AI focused on training computers to learn from data." },
  { q: "what is openai", a: "OpenAI is an AI research lab, creators of GPT models like me!" },
  { q: "what time is it", a: "Sorry, I don't have access to real-time data yet." },
  { q: "tell me a joke", a: "Why did the programmer quit his job? Because he didn't get arrays." },
  { q: "what is python", a: "Python is a high-level, interpreted programming language known for its readability." },
  { q: "what is java", a: "Java is a widely-used object-oriented programming language." },
  { q: "what is github", a: "GitHub is a platform for hosting and collaborating on code using Git." },
  { q: "what is api", a: "API stands for Application Programming Interface, allowing software to communicate." },
  { q: "what is json", a: "JSON stands for JavaScript Object Notation, a lightweight data interchange format." },
  { q: "what is rest api", a: "REST API is a web service that uses HTTP methods to interact with resources." },
  { q: "how to learn programming", a: "Start with basics, practice regularly, and build projects." },
  { q: "what is cloud computing", a: "Cloud computing provides on-demand computing resources over the internet." },
  { q: "what is docker", a: "Docker is a platform to create, deploy, and run applications in containers." },
  { q: "what is linux", a: "Linux is an open-source operating system widely used on servers and desktops." },
  { q: "what is windows", a: "Windows is a popular operating system developed by Microsoft." },
  { q: "what is macos", a: "macOS is Apple's operating system for Mac computers." },
  { q: "who is bill gates", a: "Bill Gates is the co-founder of Microsoft." },
  { q: "what is bitcoin", a: "Bitcoin is a decentralized cryptocurrency." },
  { q: "what is blockchain", a: "Blockchain is a decentralized ledger technology used in cryptocurrencies." },
  { q: "what is data science", a: "Data science is the field of extracting insights from data." },
  { q: "what is deep learning", a: "Deep learning is a subset of machine learning using neural networks." },
  { q: "what is chatbot", a: "A chatbot is a program that simulates human conversation." },
  { q: "what is api key", a: "An API key is a token used to authenticate API requests." },
  { q: "what is sql", a: "SQL is a language for managing and querying databases." },
  { q: "what is nosql", a: "NoSQL refers to non-relational databases." },
  { q: "what is firebase", a: "Firebase is a platform by Google for mobile and web app development." },
  { q: "what is react", a: "React is a JavaScript library for building user interfaces." },
  { q: "what is angular", a: "Angular is a framework for building web applications using TypeScript." },
  { q: "what is vue", a: "Vue.js is a progressive JavaScript framework for building UI." },
  { q: "what is nodejs", a: "Node.js is a runtime to execute JavaScript on the server." },
  { q: "what is npm", a: "npm is the package manager for Node.js." },
  { q: "what is typescript", a: "TypeScript is a typed superset of JavaScript." },
  { q: "what is docker compose", a: "Docker Compose lets you define and run multi-container Docker apps." },
  { q: "what is kubernetes", a: "Kubernetes is a container orchestration platform." },
  { q: "what is ai ethics", a: "AI ethics deals with the moral implications of AI technology." },
  { q: "what is vpn", a: "A VPN encrypts your internet connection and hides your IP address." },
  { q: "what is cybersecurity", a: "Cybersecurity protects systems and networks from digital attacks." },
  { q: "what is phishing", a: "Phishing is a cyber attack tricking users into revealing sensitive info." },
  { q: "what is ssl", a: "SSL secures data transferred between users and websites." },
  { q: "what is https", a: "HTTPS is HTTP over SSL/TLS, providing secure communication." },
  { q: "what is web hosting", a: "Web hosting stores websites so they can be accessed online." },
  { q: "what is domain name", a: "A domain name is a human-readable address for websites." },
  { q: "what is seo", a: "SEO is optimizing websites to rank higher in search engines." },
  { q: "what is google analytics", a: "Google Analytics tracks and reports website traffic." },
  { q: "what is digital marketing", a: "Digital marketing promotes products or services online." },
  { q: "what is cloudflare", a: "Cloudflare provides CDN and security services for websites." },
  { q: "what is ai assistant", a: "AI assistants help users by performing tasks using AI." },
  { q: "what is machine translation", a: "Machine translation automatically converts text from one language to another." },
  { q: "what is chatbot training", a: "Training chatbots involves feeding data so they can respond correctly." },
  { q: "what is sentiment analysis", a: "Sentiment analysis detects emotions in text." },
  { q: "what is computer vision", a: "Computer vision enables machines to interpret images and videos." },
  { q: "what is augmented reality", a: "AR overlays digital content onto the real world." },
  { q: "what is virtual reality", a: "VR immerses users in a fully digital environment." },
  { q: "what is iot", a: "IoT connects physical devices to the internet." },
  { q: "what is big data", a: "Big data refers to extremely large data sets." },
  { q: "what is api rate limit", a: "Rate limit restricts how many API calls can be made in a time." },
  { q: "what is git", a: "Git is a version control system to track changes in code." },
  { q: "what is github actions", a: "GitHub Actions automate software workflows." },
  { q: "what is continuous integration", a: "CI automatically tests and integrates code changes." },
  { q: "what is agile", a: "Agile is a methodology for iterative software development." },
  { q: "what is scrum", a: "Scrum is an Agile framework for managing projects." },
  { q: "what is devops", a: "DevOps integrates development and operations for faster delivery." },
  { q: "what is serverless", a: "Serverless computing runs code without managing servers." },
  { q: "what is graphql", a: "GraphQL is a query language for APIs." },
  { q: "what is rest", a: "REST is an architectural style for APIs using HTTP." },
  { q: "what is oauth", a: "OAuth is a protocol for secure authorization." },
  { q: "what is jwt", a: "JWT is a token format for securely transmitting information." },
  { q: "what is chatbot fallback", a: "Fallback is a bot's response when it doesn't understand a query." },
  { q: "what is uptime", a: "Uptime is the amount of time a system is operational." },
  { q: "what is downtime", a: "Downtime is when a system is unavailable." },
  { q: "what is load balancing", a: "Load balancing distributes traffic across servers." },
  { q: "what is dns", a: "DNS translates domain names to IP addresses." },
  { q: "what is ip address", a: "An IP address identifies a device on a network." },
  { q: "what is subnet", a: "A subnet divides a network into smaller segments." },
  { q: "what is vpn tunnel", a: "A VPN tunnel encrypts data between two endpoints." },
  { q: "what is firewall", a: "A firewall blocks unauthorized network access." },
  { q: "what is malware", a: "Malware is malicious software designed to harm systems." },
  { q: "what is ransomware", a: "Ransomware locks data and demands payment." },
  { q: "what is trojan", a: "A Trojan is malware disguised as legitimate software." },
  { q: "what is spyware", a: "Spyware secretly monitors user activity." },
  { q: "what is adware", a: "Adware displays unwanted advertisements." },
  { q: "what is botnet", a: "A botnet is a network of infected computers." },
  { q: "what is ddos attack", a: "A DDoS attack overwhelms a service with traffic." },
  { q: "what is phishing attack", a: "Phishing attacks trick users into giving sensitive info." },
  { q: "what is social engineering", a: "Social engineering manipulates people to breach security." },
  { q: "what is encryption", a: "Encryption converts data into a secure format." },
  { q: "what is decryption", a: "Decryption converts encrypted data back to original form." },
  { q: "what is ssl certificate", a: "An SSL certificate secures website data transfers." },
  { q: "what is two factor authentication", a: "2FA adds a second layer of login security." },
  { q: "what is biometrics", a: "Biometrics uses physical traits for identity verification." },
  { q: "what is cloud storage", a: "Cloud storage saves data on remote servers." },
  { q: "what is saas", a: "SaaS delivers software over the internet." },
  { q: "what is paas", a: "PaaS provides a platform for app development." },
  { q: "what is iaas", a: "IaaS offers virtualized computing resources." },
  { q: "what is vpn ip leak", a: "An IP leak exposes your real IP despite VPN use." },
  { q: "what is data mining", a: "Data mining extracts patterns from large datasets." },
  { q: "what is natural language processing", a: "NLP enables computers to understand human language." },
  { q: "what is text to speech", a: "TTS converts written text into spoken words." },
  { q: "what is speech to text", a: "STT converts spoken words into text." },
  { q: "what is chatbot conversation flow", a: "It’s the planned sequence of interactions in a chatbot." },
  { q: "what is chatbot intent", a: "Intent is the purpose behind a user’s message." },
  { q: "what is chatbot entity", a: "Entities are keywords or data extracted from user input." },
  { q: "what is chatbot context", a: "Context is previous conversation info the bot remembers." },
  { q: "what is chatbot api", a: "A chatbot API allows integration with other apps or services." },
  { q: "what is chatbot nlp", a: "NLP lets chatbots understand and process language." },
  { q: "what is chatbot fallback message", a: "A default reply when the chatbot doesn't understand." },
  { q: "what is chatbot personalization", a: "Customizing bot responses based on user data." },
  { q: "what is chatbot analytics", a: "Analytics track chatbot usage and performance." },
  { q: "what is chatbot training data", a: "Data used to teach the chatbot how to respond." },
  { q: "what is chatbot script", a: "A predefined set of bot responses and flows." },
  { q: "what is chatbot UI", a: "The interface users interact with the chatbot." },
  { q: "what is chatbot ux", a: "User experience in interacting with the chatbot." },
  { q: "what is chatbot escalation", a: "When a bot transfers the conversation to a human." },
  { q: "what is chatbot multichannel", a: "Supporting chatbot on multiple platforms." },
  { q: "what is chatbot proactive messaging", a: "Bot initiates conversation with users." },
  { q: "what is chatbot reactive messaging", a: "Bot responds to user messages." },
  { q: "what is chatbot conversation history", a: "Log of past chat interactions." },
  { q: "what is chatbot webhook", a: "A callback URL to integrate chatbot with other systems." },
  { q: "what is chatbot intent recognition", a: "Detecting user intent from messages." },
  { q: "what is chatbot sentiment analysis", a: "Determining user emotions from chat." },
  { q: "what is chatbot knowledge base", a: "A database of answers the chatbot uses." },
  { q: "what is chatbot response time", a: "Time bot takes to reply to users." },
  { q: "what is chatbot scalability", a: "Ability to handle many users simultaneously." },
  { q: "what is chatbot uptime", a: "Percentage of time chatbot is operational." },
  { q: "what is chatbot ai", a: "Artificial Intelligence integrated in chatbots." },
  { q: "what is chatbot ml", a: "Machine Learning applied to chatbots." },
  { q: "what is chatbot nlg", a: "Natural Language Generation used by chatbots." },
  { q: "what is chatbot deployment", a: "Making the chatbot live for users." },
  { q: "what is chatbot integration", a: "Connecting chatbot with other services." },
  { q: "what is chatbot maintenance", a: "Ongoing updates and fixes for the chatbot." },
  { q: "what is chatbot security", a: "Measures to protect chatbot and data." },
  { q: "what is chatbot privacy", a: "Protecting user data in chatbot conversations." },
  { q: "what is chatbot GDPR", a: "Data protection regulations relevant to chatbots." },
  { q: "what is chatbot compliance", a: "Following laws and rules in chatbot design." },
  { q: "what is chatbot feedback", a: "User responses to improve chatbot." },
  { q: "what is chatbot user retention", a: "Keeping users engaged with the chatbot." },
  { q: "what is chatbot natural conversation", a: "Chatbot talks like a real human." },
  { q: "what is chatbot multi-language support", a: "Bot understands multiple languages." },
  { q: "what is chatbot multilingual", a: "Supporting more than one language in chat." },
  { q: "what is chatbot voice recognition", a: "Bot understands spoken input." },
  { q: "what is chatbot voice response", a: "Bot replies with speech." },
  { q: "what is chatbot live chat", a: "Bot chatting alongside human agents." },
  { q: "what is chatbot omnichannel", a: "Consistent chatbot experience across channels." },
  { q: "what is chatbot conversation analysis", a: "Reviewing chats to improve bot." },
  { q: "what is chatbot escalation protocol", a: "Rules to transfer chat to humans." },
  { q: "what is chatbot virtual assistant", a: "AI assistant helping users via chat." },
  { q: "what is chatbot text analytics", a: "Extracting info from chat text." },
  { q: "what is chatbot human handoff", a: "Switching from bot to human agent." },
  { q: "what is chatbot proactive chat", a: "Bot starts the conversation." },
  { q: "what is chatbot reactive chat", a: "Bot responds to user input." },
  { q: "what is chatbot training phrases", a: "Sample inputs used to train bot." },
  { q: "what is chatbot intent mapping", a: "Linking user inputs to intents." },
  { q: "what is chatbot dialog management", a: "Handling conversation flow." },
  { q: "what is chatbot utterance", a: "A single user message." },
  { q: "what is chatbot fallback intent", a: "Intent triggered when bot fails to understand." },
  { q: "what is chatbot slot filling", a: "Gathering necessary info from users." },
  { q: "what is chatbot webhook call", a: "Bot requests external API." },
  { q: "what is chatbot integration testing", a: "Testing chatbot connected systems." },
  { q: "what is chatbot user profiling", a: "Collecting user info for personalization." },
  { q: "what is chatbot language model", a: "Model that understands and generates language." },
  { q: "what is chatbot scalability testing", a: "Testing bot under heavy load." },
  { q: "what is chatbot voice bot", a: "Bot that interacts via voice." },
  { q: "what is chatbot text bot", a: "Bot that interacts via text." },
  { q: "what is chatbot sentiment detection", a: "Detecting user mood." },
  { q: "what is chatbot intent classification", a: "Categorizing user intentions." },
  { q: "what is chatbot entity extraction", a: "Identifying key info from input." },
  { q: "what is chatbot response generation", a: "Creating replies for users." },
  { q: "what is chatbot conversation flow design", a: "Planning dialog steps." },
  { q: "what is chatbot user engagement", a: "User interaction level with bot." },
  { q: "what is chatbot ai engine", a: "Core AI powering the chatbot." },
  { q: "what is chatbot conversational ui", a: "Interface allowing chat interaction." },
  { q: "what is chatbot session management", a: "Tracking active user sessions." },
  { q: "what is chatbot user authentication", a: "Verifying user identity." },
  { q: "what is chatbot data storage", a: "Saving chat logs and user data." },
  { q: "what is chatbot compliance requirements", a: "Rules chatbot must follow." },
  { q: "what is chatbot message queue", a: "Managing message flow." },
  { q: "what is chatbot latency", a: "Delay between user input and bot reply." },
  { q: "what is chatbot nlu", a: "Natural Language Understanding." },
  { q: "what is chatbot entity resolution", a: "Resolving entities to specific values." },
  { q: "what is chatbot logging", a: "Recording chat interactions." },
  { q: "what is chatbot api integration", a: "Connecting chatbot to external APIs." },
  { q: "what is chatbot cloud hosting", a: "Running chatbot on cloud servers." },
  { q: "what is chatbot troubleshooting", a: "Fixing chatbot issues." },
  { q: "what is chatbot fallback strategy", a: "Plan for handling unknown inputs." },
  { q: "what is chatbot multi-turn conversation", a: "Handling dialogs with multiple messages." },
  { q: "what is chatbot knowledge graph", a: "A graph of interconnected information used by bots." },
  { q: "what is chatbot entity synonym", a: "Alternative names for an entity." },
  { q: "what is chatbot voice user interface", a: "User interface driven by voice commands." },
  { q: "what is chatbot message broadcasting", a: "Sending messages to multiple users." },
  { q: "what is chatbot personalization engine", a: "Component managing custom user experience." },
  { q: "what is chatbot speech synthesis", a: "Generating speech from text." },
  { q: "what is chatbot api key", a: "Token to access chatbot API." },
  { q: "what is chatbot webhook url", a: "URL to send bot events." },
  { q: "what is chatbot message template", a: "Predefined message format." },
  { q: "what is chatbot interactive message", a: "Message with buttons or actions." },
  { q: "what is chatbot auto reply", a: "Bot's automated response." },
  { q: "what is chatbot context switching", a: "Changing topic in conversation." },
  { q: "what is chatbot multi intent", a: "Handling multiple intents in one message." },
  { q: "what is chatbot slot value", a: "Specific value collected for a slot." },
  { q: "what is chatbot prompt engineering", a: "Designing effective prompts for AI bots." },
  { q: "what is chatbot open domain", a: "Chatbot without topic restrictions." },
  { q: "what is chatbot closed domain", a: "Chatbot limited to specific topics." },
  { q: "what is chatbot training pipeline", a: "Process for training chatbot models." },
  { q: "what is chatbot entity recognition", a: "Finding entities in user text." },
  { q: "what is chatbot dialogue act", a: "Purpose of a conversational turn." },
  { q: "what is chatbot utterance segmentation", a: "Dividing speech into parts." },
  { q: "what is chatbot domain adaptation", a: "Adjusting chatbot to a new domain." },
  { q: "what is chatbot intent disambiguation", a: "Clarifying multiple intents." },
  { q: "what is chatbot active learning", a: "Improving chatbot using user feedback." },
  { q: "what is chatbot confidence score", a: "Bot's certainty about an intent." },
  { q: "what is chatbot transfer learning", a: "Using pre-trained models to train chatbot." },
  { q: "what is chatbot multi modal", a: "Using multiple input types like text and images." },
  { q: "what is chatbot generative model", a: "Model generating text responses." },
  { q: "what is chatbot retrieval model", a: "Model retrieving best response from data." },
  { q: "what is chatbot human in the loop", a: "Human helps bot improve responses." },
  { q: "what is chatbot intent hierarchy", a: "Organizing intents in a hierarchy." },
  { q: "what is chatbot data annotation", a: "Labeling data for training." },
  { q: "what is chatbot conversational context", a: "Information from previous messages." },
  { q: "what is chatbot session timeout", a: "Ending a chat session after inactivity." },
  { q: "what is chatbot entity linking", a: "Connecting entities to knowledge bases." },
  { q: "what is chatbot turn taking", a: "Alternating speaker turns in chat." },
  { q: "what is chatbot active session", a: "Ongoing chat between user and bot." },
  { q: "what is chatbot multi party conversation", a: "Conversation with multiple users." },
  { q: "what is chatbot dialogue state tracking", a: "Tracking progress in dialog." },
  { q: "what is chatbot natural language generation", a: "Creating human-like text." },
  { q: "what is chatbot utterance paraphrasing", a: "Rephrasing user input." },
  { q: "what is chatbot semantic parsing", a: "Converting text to machine-readable format." },
  { q: "what is chatbot knowledge distillation", a: "Transferring knowledge to smaller models." },
  { q: "what is chatbot zero shot learning", a: "Handling tasks without direct training." },
  { q: "what is chatbot few shot learning", a: "Learning from few examples." },
  { q: "what is chatbot intent expansion", a: "Adding new intents to chatbot." },
  { q: "what is chatbot error handling", a: "Managing mistakes in conversation." },
  { q: "what is chatbot failover", a: "Backup system when bot fails." },
  { q: "what is chatbot conversational ai", a: "AI designed to converse naturally." },
  { q: "what is chatbot multi agent system", a: "Multiple bots working together." },
  { q: "what is chatbot proactive learning", a: "Bot learns proactively from data." },
  { q: "what is chatbot context window", a: "Amount of context bot uses." },
  { q: "what is chatbot dialogue policy", a: "Rules guiding chatbot responses." },
  { q: "what is chatbot natural language understanding", a: "Understanding user language." },
  { q: "what is chatbot entity disambiguation", a: "Clarifying entity meanings." },
  { q: "what is chatbot dialogue management system", a: "System managing conversation flow." },
  { q: "what is chatbot knowledge representation", a: "How knowledge is stored for bot." },
  { q: "what is chatbot model fine tuning", a: "Adjusting model for better results." },
  { q: "what is chatbot entity slot", a: "Placeholders for entity values." },
  { q: "what is chatbot dialogue turn", a: "A single exchange in conversation." },
  { q: "what is chatbot user intent", a: "Goal user wants to achieve." },
  { q: "what is chatbot entity type", a: "Category of an entity." },
  { q: "what is chatbot semantic role labeling", a: "Assigning roles in a sentence." },
  { q: "what is chatbot conversational context tracking", a: "Keeping track of conversation state." },
  { q: "what is chatbot entity value normalization", a: "Standardizing entity values." },
  { q: "what is chatbot utterance classification", a: "Categorizing user inputs." },
  { q: "what is chatbot intent recognition system", a: "System that detects user intent." },
  { q: "what is chatbot conversation summarization", a: "Summarizing chat sessions." },
  { q: "what is chatbot dialog act recognition", a: "Identifying purpose of utterance." },
  { q: "what is chatbot entity extraction model", a: "Model extracting entities from text." },
  { q: "what is chatbot sentiment classification", a: "Classifying emotions in text." },
  

    ];

    // Function to match user input with knowledge base (simple contains match)
    function getBotReply(inputText) {
      if (!inputText) return "Please say something!";
      const cleaned = inputText.toLowerCase().trim();

      // Check knowledge base for partial matches
      for (const pair of knowledgeBase) {
        if (cleaned.includes(pair.q)) {
          return pair.a;
        }
      }

      return "Sorry, I don't understand that. Can you try asking differently?";
    }

    function appendMessage(text, sender) {
      const div = document.createElement('div');
      div.className = `message ${sender}`;
      div.textContent = text;
      chatbox.appendChild(div);
      chatbox.scrollTop = chatbox.scrollHeight;
    }

    function sendMessage() {
      const message = input.value.trim();
      if (!message) return;
      appendMessage(message, 'user');
      input.value = '';
      send.disabled = true;

      // Simulate typing delay
      appendMessage('...', 'bot');

      setTimeout(() => {
        // Remove typing indicator
        const lastMessage = chatbox.querySelector('.message.bot:last-child');
        if(lastMessage && lastMessage.textContent === '...') {
          lastMessage.remove();
        }

        const reply = getBotReply(message);
        appendMessage(reply, 'bot');
        send.disabled = false;
        input.focus();
      }, 900);
    }

    send.addEventListener('click', sendMessage);
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') sendMessage();
    });

    // Focus input on load
    input.focus();